services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000 # Local Host
    command: gunicorn copypasta_celery.wsgi:application -b 0.0.0.0:8000 # Webserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  worker:
    build: .
    command: celery -A copypasta_celery worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web